extends:
  - eslint:recommended
  - next/core-web-vitals
  - next
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:prettier/recommended
plugins:
  - prettier
  - "@typescript-eslint"
rules:
  indent: 0
  react/no-unescaped-entities: 0
  react/react-in-jsx-scope: 0
  "@typescript-eslint/ban-ts-comment": 0
  "@typescript-eslint/no-explicit-any": 0
settings:
  react:
    version: detect
  import/resolver:
    alias:
      map:
        - ["@", "./"]
      extensions: [".ts", ".tsx", ".js"]
